openapi: 3.1.0
info:
  version: 1.0.0
  title: The Best links app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is documentation of The Best links app
tags:
  - name: links
    description: Operations about links.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://the-best-link-backend.onrender.com
paths:
  /links:
    get:
      $ref: ../swagger/paths/links/get.yaml
    post:
      $ref: ../swagger/paths/links/post.yaml
  /links/{id}:
    get:
      $ref: ../swagger/paths/links/{id}/get.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
